### ISSUE TITLE
IBC transfer errors between Osmosis and Konstellation

### ISSUE THREAD

**Issue by andynog** [Konstellation/konstellation#14]
Hi guys, not sure if this is reported or not or if some people are already aware, but I've noticed a lot of ibc transfer errors between Osmosis <-> Konstellation (https://www.mintscan.io/konstellation/relayers/channel-0)

I don't know the specifics of the implementation, but just letting you know since the errors are pretty long on Mintscan and seems that something is crashing with the message `recovered: runtime error: invalid memory address or nil pointer dereference stack`

Like this one
https://www.mintscan.io/konstellation/txs/820CEF52E79E5ADE2235B0B7C3996E35465BC4AAAF12814EA7E5FC4DED871160

**Comment by shawayush** [comment]
Thank you for reporting the issue @andynog 
we have figured out the problem and solution related to it. It mainly due to [IBC tansferkeepers ](https://github.com/knstl/konstellation/blob/sdk0.45.9/app/app.go#L305)  
we will push a update soon!

**Comment by cryptonetD** [comment]
What is the expected date of the fix, any news? I tried to contact You with the same issue on discord, with no luck. Any updates?

**Comment by shawayush** [comment]
@cryptonetD  We have send already send a patch that solves the issue and would be done by this week!
thanks!
