### ISSUE TITLE
Once the full node is fully installed i always get this error when starting. I'm on version v0.5.0

### ISSUE THREAD

**Issue by Femkecl** [Konstellation/konstellation#8]
10:32AM INF starting ABCI with Tendermint
10:32AM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:32AM INF Starting localClient service connection=query impl=localClient module=abci-client
10:32AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:32AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:32AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:32AM INF Starting EventBus service impl=EventBus module=events
10:32AM INF Starting PubSub service impl=PubSub module=pubsub
10:32AM INF Starting IndexerService service impl=IndexerService module=txindex
10:32AM INF ABCI Handshake App Info hash="^�O��_�?'�L\x10sh��\vg�\vG(�^Z\u009e��ϸ\u007f" height=1 module=consensus protocol-version=0 software-version=0.5.0
10:32AM INF ABCI Replay Blocks appHeight=1 module=consensus stateHeight=1 storeHeight=2
10:32AM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 5EA54F86985FF33F27F24C107368FBB20B67940B4728A35E5AC29EBFDECFB87F, got C351BD7341A5B961027D315E7365849D556B84BF6BDBA5D2D6C06A013C71D700

**Comment by digitaladapt** [comment]
My understanding (which could be wrong), is that you need to be on the correct version for the block-chain height that you are currently at. Since you're starting a full-node from scratch, you'll have to use the older version (at least at first).

Give this a try (in your konstellation folder):
```
# Switch to "v0.4.3"
git checkout v0.4.3
# then a get the dependencies setup for that version
make build
# a will probably be needed "unsafe-reset-all"
build/knstld unsafe-reset-all
# and try the start command again.
build/knstld start
```

Good luck, let me know how it goes.

**Comment by Knstld** [comment]
This problem has been solved, see comment above and updated documentation, closing ticket.
